services:
  mysql:
    image: mysql:5.6
    container_name: mi-mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mi_database
      MYSQL_USER: usuario
      MYSQL_PASSWORD: pass1234
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
