services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: mi-api
    depends_on:
      - mysql
    env_file:
      - api/.env
    ports:
      - "3000:3000"
    volumes:
      - src-api:/app
    networks:
      - tontisbank-network
    restart: unless-stopped
    develop:
      watch:
        - action: sync+restart
          path: ./api
          target: /app
          ignore:
            - ./api/node_modules/

  mysql:
    image: mysql:5.6
    container_name: mi-mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mi_database
      MYSQL_USER: usuario
      MYSQL_PASSWORD: pass1234
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - tontisbank-network

networks:
  tontisbank-network:
    driver: bridge
    

volumes:
  mysql-data:
  src-api:
