name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: write
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high

      - name: Install dependencies
        working-directory: ./api
        run: npm ci
        
      - name: Check for vulnerabilities
        uses: oke-py/npm-audit-action@v2
        with:
          audit_level: critical
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: oke-py
          issue_labels: vulnerability,test
          dedupe_issues: true
          working_directory: ./api
